---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (Fedora)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Fedora"


- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
