- name: install apache and php for Fedora servers
  tags: apache,fedora,httpd
  dnf:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache service
  tags: apache,fedora,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy deafault file for apache
  tags: apache,httpd,apache2
  copy:
    src: /home/sasuke/ansible_tutorial/roles/web_servers/files/default_apache.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664

