  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgqw67lnPg5ha97+qcG1FriQZAMPy/ceji/fSYSVIqk sasuke@localhost.localdomain"
